"""channel model fixed

Revision ID: 6dfed6ee4ece
Revises: db7d5a95fbc0
Create Date: 2023-04-21 19:44:38.900597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfed6ee4ece'
down_revision = 'db7d5a95fbc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
