"""channel model fixed

Revision ID: ecef85947119
Revises: 6dfed6ee4ece
Create Date: 2023-04-21 19:48:54.392198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecef85947119'
down_revision = '6dfed6ee4ece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
